### ISSUE TITLE
SPINNY hangs

### ISSUE THREAD

**Issue by benp175** [dragozzine/multimoon#17]
https://github.com/dragozzine/multimoon/blob/5eb6141a8d44701c7dd80b8951a986e65140741a/src/mm_SPINNY/cashkarp.hpp#L480-L497

Mostly just leaving this as a note to myself of where SPINNY hangs. This is the only place where a loop happens, hence the only place where a (near) infinite loop can happen. I would love to implement a method for halting the integration if this loops too many times, but not sure the best way to implement this. 

Some ideas:
- Have a counter that increments after every failure and have it cancel at a certain number. But how many fails is appropriate??
- Set a minimum h0, below which the integration will just fail. Again what minimum h0 is appropriate?

Another issue is how to communicate the failure to the rest of SPINNY/MultiMoon. It would probably just suffice to set all values of arr0 to NAN. Then a simple if statement could ensure that the integration didn't fail. The if statement would then provide -inf to spinny. 

An additional problem is whether parameter sets that cause a hang should be rejected. In most cases of hangs, SPINNY is probably trying to resolve a collision, which we know should be rejected. There could be some conditions caused by numerical issues/tolerance issues which shouldn't be rejected, but that's probably not really a problem.

**Comment by benp175** [comment]
I've done some thorough investigation and found that setting a minimum timestep is likely the best solution. I've designed a fix that detects when the timestep goes below 1e-5 seconds and quits the integration. From some, albeit brief, testing, it looks like the actual value of a minimum timestep is not really important... Problems seem be all or nothing, as in timesteps are reasonable or really tiny (like 1e-17 tiny), without much in between. This should allow for a drastic reduction in the number of hangs inside of SPINNY.

I'm testing it more rigorously right now and will push it once the tests are completed.

**Comment by dragozzine** [comment]
Yes, presumably SPINNY hangs when the integrator thinks it needs to reduce the step size to a very small value and then takes an absurdly long time. 

h0 and time may not be exactly the same, so I'm not sure if you have actually determined that the units are in 1e-5 seconds or that this is the value of h0. If there is a strong bifurcation between "normal" and "hang" and you've found the threshold between these, then that seems fine. 

Another option is to force (if possible?) Cash-Karp to use the existing stepsize even if it breaks the tolerance. Then it will presumably do an integration which may not necessarily be faithful to the actual physics, but at least will run in a reasonable amount of time and be an okay approximation. Another option is, once the stepsize gets unreasonably small, increase the tolerance so that it eventually succeeds, again with the idea. 

But overall, no system should have a set of realistic parameters that makes the integration exceedingly difficult, so just stopping and returning NaNs (and then returning -inf for the likelihood) is, I think, an excellent and practical solution. Its like having a prior that says "SPINNY should be able to integrate this without taking a REALLY long time". I suppose we don't KNOW that this is the case, but it seems likely. 

If we can confirm that the issue really is objects getting really close together, then we could in theory implement basic collision checking. We know (or can estimate) the sizes of the objects, even sizes that are extremely conservative. No TNB we are working on is going to have two centers-of-mass get within 10 km of each other, for example. This might be more general: perhaps there are runs where the objects get unreasonably close together but SPINNY doesn't hang, so we let it go (but presumably these are really bad fits too). 

Any of these solutions should be great for now and keep MultiMoon going even when it tests really bad parameters.

**Comment by benp175** [comment]
There does seem to be a bifurcation of "normal" and "hang" that seems to be pretty robust. With more thought, I've realized that even if we are rejecting a good parameter set (probably not though) that it happens pretty infrequently. I'm running a 110 run right now for Lempo, which never used to work for SPINNY, and I'm having a rejected integration (by violating a minimum timestep condition) happen once every ~50000-100000 steps, which is so small that it doesn't matter. It also seems to be pretty robustly capturing every bad integration, and given the rate of rejection, it's likely not rejecting good steps.

As for the other methods, it might be possible, but I'm mostly constrained by the set up of SPINNY. Without some fairly significant modifications to the overall set up, it'll be pretty difficult to implement the other methods. I think for now, a minimum timestep (definitely in seconds!) should be adequate. If it needs to change, it's a simple modification that can be quickly done. Ideally, I would like to put it in the runprops, but adding that in requires tinkering with the Cython part of SPINNY, which I have no experience with.

**Comment by benp175** [comment]
I've pushed my fix to the main branch. It's been working flawlessly in my tests so far, so it should be a game changer for challenging systems like Lempo.
